id: A751CC56B
title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
  of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
type: translation
pechas:
- I3F2D2630
- I23F6B94D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:27.247538
  last_modified_at: 2023-01-04 11:35:27.247548
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3F2D2630/A762: 919C
  I23F6B94D/9BEB: 919C
